// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx';
import * as $_app from './routes/_app.tsx';
import * as $api_auth_login from './routes/api/auth/login.ts';
import * as $api_auth_logout from './routes/api/auth/logout.ts';
import * as $api_auth_register from './routes/api/auth/register.ts';
import * as $api_joke from './routes/api/joke.ts';
import * as $greet_name_ from './routes/greet/[name].tsx';
import * as $index from './routes/index.tsx';
import * as $login from './routes/login.tsx';
import * as $logout from './routes/logout.ts';
import * as $register from './routes/register.tsx';
import * as $Counter from './islands/Counter.tsx';
import * as $LanguageSwitcher from './islands/LanguageSwitcher.tsx';
import * as $MobileMenu from './islands/MobileMenu.tsx';
import * as $ProductCard from './islands/ProductCard.tsx';
import * as $ProductShowcaseCarousel from './islands/ProductShowcaseCarousel.tsx';
import * as $TestimonialsCarousel from './islands/TestimonialsCarousel.tsx';
import type { Manifest } from '$fresh/server.ts';

const manifest = {
  routes: {
    './routes/_404.tsx': $_404,
    './routes/_app.tsx': $_app,
    './routes/api/auth/login.ts': $api_auth_login,
    './routes/api/auth/logout.ts': $api_auth_logout,
    './routes/api/auth/register.ts': $api_auth_register,
    './routes/api/joke.ts': $api_joke,
    './routes/greet/[name].tsx': $greet_name_,
    './routes/index.tsx': $index,
    './routes/login.tsx': $login,
    './routes/logout.ts': $logout,
    './routes/register.tsx': $register,
  },
  islands: {
    './islands/Counter.tsx': $Counter,
    './islands/LanguageSwitcher.tsx': $LanguageSwitcher,
    './islands/MobileMenu.tsx': $MobileMenu,
    './islands/ProductCard.tsx': $ProductCard,
    './islands/ProductShowcaseCarousel.tsx': $ProductShowcaseCarousel,
    './islands/TestimonialsCarousel.tsx': $TestimonialsCarousel,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
